name: build-windows

permissions:
  contents: write

on:
  push:
    paths:
      - "VERSION"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4

    - name: Get version tag
      shell: pwsh
      run: |
        $version = Get-Content -Path "VERSION"
        echo "VERSION=$version" >> $env:GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install dependencies
      run: |
        cd src
        go mod download

    - name: Build
      run: |
        cd src
        go build -v -ldflags="-s -w -H=windowsgui -extldflags=-static" -o 1.exe .
      env:
        CGO_ENABLED: 1
        GOAMD64: v1

    - name: Add icon, manifest, and version info
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile reshacker_setup.zip https://github.com/user-attachments/files/18878075/reshacker_setup.zip
        Expand-Archive -DestinationPath reshacker_setup reshacker_setup.zip
        reshacker_setup/reshacker_setup.exe /SILENT
        Start-Sleep -Seconds 60
        Invoke-Expression "& `"$Env:P`" -open src/1.exe -save src/2.exe -action addoverwrite -res images/lock.ico -mask `"ICONGROUP,MAINICON,`""
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open src/2.exe -save src/3.exe -action addoverwrite -res images/lock.ico -mask `"ICONGROUP,GLFW_ICON,`""
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open src/3.exe -save src/4.exe -action addoverwrite -res dist/windows/manifest.xml -mask `"MANIFEST,1,`""
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open dist/windows/versioninfo.rc -save resources.res -action compile"
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open src/4.exe -save src/5.exe -action addoverwrite -res resources.res"
        Start-Sleep -Seconds 30
      env:
        P: "C:\\Program Files (x86)\\Resource Hacker\\ResourceHacker.exe"

    - name: Compress with upx
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile upx.zip https://github.com/upx/upx/releases/download/v5.0.2/upx-5.0.2-win64.zip
        Expand-Archive -DestinationPath upx upx.zip
        upx/upx-5.0.2-win64/upx.exe --lzma -o src/ZeeCrypt.exe src/5.exe

    - name: Install WiX
      shell: pwsh
      run: |
        dotnet tool install --global wix --version 5.0.2
        wix extension add WixToolset.UI.wixext/5.0.2

    - name: Build installer (MSI)
      shell: pwsh
      run: |
        wix build dist/windows/installer.wxs `
          -arch x64 `
          -ext WixToolset.UI.wixext `
          -d ExePath=src/ZeeCrypt.exe `
          -d IconPath=images/lock.ico `
          -d LicenseRtfPath=dist/windows/License.rtf `
          -d ProductVersion="$($env:VERSION).0.0" `
          -o ZeeCrypt-Installer.msi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: |
          src/*.exe
          ZeeCrypt-Installer.msi
        if-no-files-found: error
        compression-level: 9

    - name: Generate checksums
      shell: pwsh
      run: |
        $exeHash = Get-FileHash "src/ZeeCrypt.exe" -Algorithm SHA256
        echo "CHECKSUM_ZEECRYPT=$($exeHash.Hash)" >> $env:GITHUB_ENV
        $msiHash = Get-FileHash "ZeeCrypt-Installer.msi" -Algorithm SHA256
        echo "CHECKSUM_INSTALLER=$($msiHash.Hash)" >> $env:GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          src/ZeeCrypt.exe
          ZeeCrypt-Installer.msi
        tag_name: ${{ env.VERSION }}
        make_latest: true
        append_body: true
        body: |
          **Windows:**
          `sha256(ZeeCrypt.exe)  ${{ env.CHECKSUM_ZEECRYPT }}`
          `sha256(ZeeCrypt-Installer.msi)  ${{ env.CHECKSUM_INSTALLER }}`
