name: pr-test-build-windows

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  pr-test-build-windows:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Install dependencies
      run: |
        cd src
        go mod download

    - name: Build
      run: |
        cd src
        go build -v -ldflags="-s -w -H=windowsgui -extldflags=-static" -o 1.exe .
      env:
        CGO_ENABLED: 1
        GOAMD64: v1

    - name: Add manifest and version info
      run: |
        cd src
        go tool go-winres patch --in winres/winres.json --no-backup 1.exe

    - name: Compress with upx
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile upx.zip https://github.com/upx/upx/releases/download/v5.0.2/upx-5.0.2-win64.zip
        Expand-Archive -DestinationPath upx upx.zip
        upx/upx-5.0.2-win64/upx.exe --lzma -o src/ZeeCrypt.exe src/1.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr-test-build-windows-ONLY-FOR-TESTING
        path: src/*.exe
        if-no-files-found: error
        compression-level: 9
